config/routes.rb
Rails.application.routes.draw do

  root to: "pages#index"
  resources :games
  get "/search", to: "searches#index"
  get "/allgames", to: "games#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

    def index
        @games = Game.all.order(id: :desc)
    end

    def show
        @game = Game.find(params[:id])
    end

    def new
       @game = Game.new
    end

    def create
       @game = Game.new(game_params)
       if @game.save
         redirect_to(games_path)
       else
         render(:new)
       end
    end

    def edit
        @game = Game.find(params[:id])
    end

    def update
        @game = Game.find(params[:id])
        if @game.update(game_params)
            redirect_to(games_path)
        else
            render(:edit)
        end
    end

    def destroy
        @game = Game.find(params[:id])
        @game.destroy
        redirect_to(games_path)

    end

    private
    #strong_params
    def game_params
        params.require(:game).permit(:title, :release_date, :rating, :console)
    end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def index
        @games = Game.limit(10).order(created_at: :desc)
    end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

    def index

        @query = params[:q]
        @games = Game.where("title ILIKE ?", "%#{@query}%").order(created_at: :desc)
        
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/games/_game_form.html.erb
<p>
<%= form_thing.label(:title) %>
<%= form_thing.text_area(:title) %>
<br>
<%= form_thing.label(:release_date) %>
<%= form_thing.date_field(:release_date) %>
<br>
<%= form_thing.label(:rating) %>
<%= form_thing.number_field(:rating, in: 0.0..10.0, step: 0.1) %>
<br>
<%= form_thing.label(:console) %>
<%= form_thing.select(:console, options_for_select([['Xbox'], ['Playstation'], ['Nintendo'], ['PC', 3]])) %>
</p>

app/views/games/_games.html.erb
<% games.each do |game| %> 
    <div class = "game-card">
    <p> 
    <%= game.title %>
    -
    <%= game.rating %>
    -
    <%= link_to("View Info.", game_path(game.id))%>
    </p>
    </div>
<% end %>

app/views/games/edit.html.erb
<%= form_for(@game) do |f| %>
    <%= render("game_form", form_thing: f) %>
    <%= f.submit("Update") %>
<% end %>

app/views/games/index.html.erb
<% @games.each do |game| %>
    <div class="game-card">
    <p>
    <%= game.title %>
    -
    <%= link_to("View Info.", game_path(game.id))%>
    -
    <%= link_to("edit", edit_game_path(game.id))%>
    -
    <%= link_to("delete", game_path(game.id), method: :delete, data: {confirm: "Are you really sure you want to delete this game?"}) %>
    </p>
    </div>
<% end %>

app/views/games/new.html.erb
<%= form_for(@game) do |f| %>
    <%= render("game_form", form_thing: f) %>
    <%= f.submit("Save") %>
<% end %>

app/views/games/show.html.erb
<% game = @game %>

<%= game.title %>
<br>
<%= game.console %>
<br>
<%= game.release_date %>
<br>
<%= game.rating %>
<br>
<li><%= link_to("Back", :back) %></li>
<li><%= link_to("edit", edit_game_path(game.id))%></li>
<li><%= link_to("delete", game_path(game.id), method: :delete, data: {confirm: "Are you really sure you want to delete this game?"}) %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IGDb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

     <%= render("shared/search_form") %>
    <nav>
      <li><%= link_to("Home", root_path) %></li>
      <li><%= link_to("Add Game", new_game_path) %></li>
      <li><%= link_to("View Games", games_path) %></li>

    </nav>

    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Welcome to the IGDb</h1>
<h2>Top 10 games in the World:</h2>
<%= render("games/games", games: @games) %>

app/views/searches/index.html.erb
<h1>Search for '<%=@query%>'</h2>

<% @games.each do |game| %>
    <div class="game-card">
    <p>
    <%= game.title %>
    -
    <%= link_to("View Info.", game_path(game.id))%>
    </div>
<% end %>

app/views/shared/_search_form.html.erb
<%= form_with(url: search_path, method: :get, local:true ) do |f| %>
    <%= f.text_field(:q) %>
    <%= f.submit("Search") %>
<% end %>